/**
 * PR Builder Utility
 * Assembles Pull Requests with builder outputs, QA results, and change records
 */

import { Octokit } from 'octokit'
import { github } from './client'
import { PRContext, ChangeRecord, ComplianceResult } from '@/types/build-sequence'
import { QAResult, BuilderTask } from '@/types/builder'

/**
 * Generate PR title from context
 */
export function generatePRTitle(context: PRContext): string {
  const { builderOutputs } = context
  
  if (builderOutputs.length === 0) {
    return 'Automated Build Sequence Updates'
  }
  
  // Extract unique modules from builder outputs
  const modules = new Set<string>()
  builderOutputs.forEach(output => {
    if (output.input?.module) {
      modules.add(output.input.module)
    }
  })
  
  if (modules.size === 1) {
    return `feat(${Array.from(modules)[0]}): Automated build sequence implementation`
  } else if (modules.size > 1) {
    return `feat: Automated build sequence updates (${modules.size} modules)`
  }
  
  return 'feat: Automated build sequence implementation'
}

/**
 * Generate PR description with all relevant information
 */
export function generatePRDescription(context: PRContext): string {
  const sections: string[] = []
  
  // Header
  sections.push('# Automated Build Sequence')
  sections.push('')
  sections.push('This PR was generated by the Foreman build sequence orchestrator.')
  sections.push('')
  
  // Summary
  sections.push('## Summary')
  sections.push('')
  sections.push(context.description || 'Automated implementation based on architecture analysis.')
  sections.push('')
  
  // Builder Outputs
  if (context.builderOutputs.length > 0) {
    sections.push('## Builder Outputs')
    sections.push('')
    
    context.builderOutputs.forEach((output, index) => {
      sections.push(`### ${index + 1}. ${output.builder || 'Unknown'} Builder`)
      sections.push('')
      sections.push(`**Module:** ${output.input?.module || 'N/A'}`)
      sections.push(`**Task:** ${output.input?.taskDescription || 'N/A'}`)
      sections.push(`**Status:** ${output.status}`)
      sections.push('')
      
      if (output.output?.artifacts && output.output.artifacts.length > 0) {
        sections.push('**Artifacts:**')
        output.output.artifacts.forEach((artifact: any) => {
          sections.push(`- ${artifact.type}: ${artifact.name}`)
        })
        sections.push('')
      }
    })
  }
  
  // Change Records
  if (context.changeRecords.length > 0) {
    sections.push('## Changes')
    sections.push('')
    
    const additions = context.changeRecords.filter(r => r.type === 'addition')
    const modifications = context.changeRecords.filter(r => r.type === 'modification')
    const deletions = context.changeRecords.filter(r => r.type === 'deletion')
    
    if (additions.length > 0) {
      sections.push('### Added')
      additions.forEach(record => {
        sections.push(`- \`${record.file}\`: ${record.description}`)
      })
      sections.push('')
    }
    
    if (modifications.length > 0) {
      sections.push('### Modified')
      modifications.forEach(record => {
        sections.push(`- \`${record.file}\`: ${record.description}`)
      })
      sections.push('')
    }
    
    if (deletions.length > 0) {
      sections.push('### Removed')
      deletions.forEach(record => {
        sections.push(`- \`${record.file}\`: ${record.description}`)
      })
      sections.push('')
    }
  }
  
  // QA Results
  if (context.qaResults.length > 0) {
    sections.push('## QA Results')
    sections.push('')
    
    const passed = context.qaResults.filter(r => r.status === 'passed')
    const failed = context.qaResults.filter(r => r.status === 'failed')
    const warnings = context.qaResults.filter(r => r.status === 'warning')
    
    sections.push(`- ✅ Passed: ${passed.length}`)
    sections.push(`- ❌ Failed: ${failed.length}`)
    sections.push(`- ⚠️ Warnings: ${warnings.length}`)
    sections.push('')
    
    if (failed.length > 0) {
      sections.push('### Failed Checks')
      failed.forEach(result => {
        sections.push(`- **${result.check}**: ${result.message}`)
      })
      sections.push('')
    }
    
    if (warnings.length > 0) {
      sections.push('### Warnings')
      warnings.forEach(result => {
        sections.push(`- **${result.check}**: ${result.message}`)
      })
      sections.push('')
    }
  }
  
  // Compliance Results
  if (context.complianceResults.length > 0) {
    sections.push('## Compliance')
    sections.push('')
    
    context.complianceResults.forEach(result => {
      const icon = result.status === 'passed' ? '✅' : result.status === 'failed' ? '❌' : '⚠️'
      sections.push(`${icon} **${result.check}**: ${result.message}`)
    })
    sections.push('')
  }
  
  // Footer
  sections.push('---')
  sections.push('')
  sections.push('🤖 *Generated by Maturion Foreman*')
  
  return sections.join('\n')
}

/**
 * Extract change records from builder outputs
 */
export function extractChangeRecords(builderOutputs: BuilderTask[]): ChangeRecord[] {
  const records: ChangeRecord[] = []
  
  builderOutputs.forEach(output => {
    if (output.output?.artifacts) {
      output.output.artifacts.forEach((artifact) => {
        records.push({
          type: 'addition', // Default to addition, could be enhanced
          file: artifact.path || artifact.name,
          description: artifact.name || 'Builder artifact',
          builder: output.builder,
          taskId: output.id
        })
      })
    }
  })
  
  return records
}

/**
 * Generate compliance results from QA results
 */
export function generateComplianceResults(qaResults: QAResult[]): ComplianceResult[] {
  const complianceResults: ComplianceResult[] = []
  
  // Governance compliance
  complianceResults.push({
    check: 'Governance Rules',
    status: 'passed',
    message: 'All governance rules enforced during build sequence'
  })
  
  // QA compliance
  const qaFailed = qaResults.filter(r => r.status === 'failed').length
  complianceResults.push({
    check: 'QA Validation',
    status: qaFailed === 0 ? 'passed' : 'warning',
    message: qaFailed === 0 
      ? 'All QA checks passed' 
      : `${qaFailed} QA check(s) require attention`
  })
  
  // Code review compliance
  complianceResults.push({
    check: 'Code Review',
    status: 'passed',
    message: 'Automated code generation follows established patterns'
  })
  
  return complianceResults
}

/**
 * Create a Pull Request with assembled context
 */
export async function createPullRequest(
  owner: string,
  repo: string,
  branch: string,
  baseBranch: string,
  context: PRContext
): Promise<string> {
  console.log('[PRBuilder] Creating pull request...')
  
  const title = context.title || generatePRTitle(context)
  const body = generatePRDescription(context)
  
  try {
    const response = await github.rest.pulls.create({
      owner,
      repo,
      title,
      body,
      head: branch,
      base: baseBranch
    })
    
    console.log(`[PRBuilder] Pull request created: ${response.data.html_url}`)
    return response.data.html_url
    
  } catch (error) {
    console.error('[PRBuilder] Failed to create pull request:', error)
    throw error
  }
}

/**
 * Update an existing Pull Request
 */
export async function updatePullRequest(
  owner: string,
  repo: string,
  prNumber: number,
  context: Partial<PRContext>
): Promise<void> {
  console.log('[PRBuilder] Updating pull request...')
  
  try {
    const updates: any = {}
    
    if (context.title) {
      updates.title = context.title
    }
    
    if (context.description || context.builderOutputs || context.qaResults) {
      const fullContext: PRContext = {
        title: context.title || '',
        description: context.description || '',
        builderOutputs: context.builderOutputs || [],
        qaResults: context.qaResults || [],
        changeRecords: context.changeRecords || [],
        complianceResults: context.complianceResults || []
      }
      updates.body = generatePRDescription(fullContext)
    }
    
    await github.rest.pulls.update({
      owner,
      repo,
      pull_number: prNumber,
      ...updates
    })
    
    console.log(`[PRBuilder] Pull request #${prNumber} updated`)
    
  } catch (error) {
    console.error('[PRBuilder] Failed to update pull request:', error)
    throw error
  }
}

/**
 * Assemble complete PR context from build sequence
 */
export function assemblePRContext(
  builderOutputs: BuilderTask[],
  qaResults: QAResult[],
  description?: string
): PRContext {
  const changeRecords = extractChangeRecords(builderOutputs)
  const complianceResults = generateComplianceResults(qaResults)
  
  return {
    title: '',
    description: description || 'Automated implementation from build sequence',
    builderOutputs,
    qaResults,
    changeRecords,
    complianceResults
  }
}
